version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: localhost/intersection-observer-demo:latest
    container_name: intersection-observer
    ports:
      - "10000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network
    volumes:
      - ./:/usr/share/nginx/html:ro
      # Uncomment below if you want to customize nginx config
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  app-network:
    driver: bridge
